name: OpenAPI Docs in PR
description: View your OpenAPI Docs as a comment in your PR
inputs:
  spec-paths:
    description: The paths to the OpenAPI specs to process (single glob or array of globs)
    required: true
  github-token:
    description: Your GitHub token to allow the action to create PR comments
    required: true
  converter-options:
    description: Optionally pass options to the widdershins OpenAPI docs converter
    required: false
runs:
  using: node12
  main: dist/index.js
