name: OpenAPI Review
author: Blake Mealey
description: Review OpenAPI spec diffs and docs in your PRs
inputs:
  spec-paths:
    description: The paths to the OpenAPI specs to process (single glob or array of globs)
    required: true
  github-token:
    description: Your GitHub token to allow the action to create PR comments
    required: true
  converter-options:
    description: Optionally pass options to the widdershins OpenAPI docs converter
    required: false
  fail-on-breaking-changes:
    description: Whether or not to fail, defaults to true
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  color: green
  icon: search
