on: [pull_request]

jobs:
  post_openapi_docs:
    runs-on: ubuntu-latest
    name: Review all OpenAPI specs
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Review OpenAPI specs
        id: review_oas
        uses: ./
        with:
          spec-paths: ./fixtures/api-with-examples.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
