on: [pull_request]

jobs:
  post_openapi_docs:
    runs-on: ubuntu-latest
    name: Post the OpenAPI docs to the PR in a comment
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Post OpenAPI docs
        id: post_openid
        uses: ./
        with:
          spec-paths: ./fixtures/api-with-examples.yaml
          github-token: ${{ secrets.GITHUB_TOKEN }}
